# Examples for learning Github Actions

name: Example 1

# Manual activation
on: [workflow_dispatch]

jobs:
  
  # -- Execution of script 1
  exec-01:
    
    runs-on: ubuntu-20.04

    steps:
      # -- Checkout the repo
      - name: Checkout!
        uses: actions/checkout@v2

      # -- Execute the script 01
      - name: Run Script-01.sh
        id: script_01
        run: |
           echo "Let's execute script-01"
           ./script-01.sh
           echo "Done!"
           version=$(cat VERSION)
           echo "VERSION: $version"
           echo "VERSION=$version" >> $GITHUB_ENV
           # echo "::set-output name=version::$version"
           # echo "::set-env name=VERSION::$version"

      - name: Testing env variables
        run: |
           # echo "Version2: ${{ steps.script_01.outputs.version }}"
           echo "Version3: ${{ env.VERSION }}"

      # -- Release!
      - name: Release!
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}"
          release_name: ${{ env.VERSION }}"
          body: |
            This is just a test...
            Testing...
          draft: true
          prerelease: false

      - name: Showing Upload URL
        run: |
          echo "URL for uploading: ${{ steps.create_release.outputs.upload_url }}"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./files.txt
          asset_name: files.txt
          asset_content_type: text/plain
 
