# Examples for learning Github Actions

name: Example 1

# Manual activation
on: [workflow_dispatch]

jobs:
  
  # -- Execution of script 1
  exec-01:
    
    runs-on: ubuntu-20.04

    steps:
      # -- Checkout the repo
      - name: Checkout!
        uses: actions/checkout@v2

      # -- Execute the script 01
      - name: Run Script-01.sh
        run: |
           echo "Let's execute script-01"
           ./script-01.sh
           echo "Done!"
           echo "Github ref: ${{ github.ref }}"

      # -- Release!
      - name: Release!
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: v0.0.1-Testing!
          body: |
            This is just a test...
            Testing...
          draft: true
          prerelease: false
          